name: 'Automatically change the year and availability each month'

on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  reset-availability:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Check
        uses: actions/checkout@v4

      - name: Update availability
        run: |
          node <<'EOF'
          const fs = require('fs');

          const filePath = './apiData.blockdev';
          
          const raw = fs.readFileSync(filePath, 'utf8');
          const data = JSON.parse(raw);

          const availability = data.response.availability;
          
          const months = [
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July',
            'August',
            'September',
            'October',
            'November',
            'December'
          ];

          const now = new Date();
          
          const currentMonthIndex = now.getUTCMonth();
          const currentYear = now.getUTCFullYear();

          const newAvailability = {};

          for (const [key, value] of Object.entries(availability)) {
            const [month, yearStr] = key.split(' ');
            
            let year = parseInt(yearStr, 10);

            const monthIndex = months.indexOf(month);

            const isPast = year < currentYear || (year === currentYear && monthIndex < currentMonthIndex);

            let newKey = key;
            let newValue = value;

            if (isPast) {
              currentYear += 1

              const maxAmount = value.amount.split('/')[1];

              newKey = `${month} ${year}`;

              newValue = {
                available: 'Available for invites',
                hexcode: '#1ac31f',
                amount: `0/${maxAmount}`
              };

              console.log(`[UPDATED] ${key} -> ${newKey}`);
            }

            newAvailability[newKey] = newValue;
          }

          const sortedKeys = Object.keys(newAvailability).sort((a, b) => {
            const [monthA, yearA] = a.split(' ');
            const [monthB, yearB] = a.split(' ');

            if (parseInt(yearA) !== parseInt(yearB)) {
              return parseInt(yearA) - parseInt(yearB);
            }

            return months.indexOf(monthA) - months.indexOf(monthB);
          });

          const sortedAvailability = {};

          for (const key of sortedKeys) {
            sortedAvailability[key] = newAvailability[key];
          }

          data.response.availability = sortedAvailability;

          fs.writeFileSync(
            filePath,
            JSON.stringify(data, null, 4) + '\n',
            'utf8'
          );

          console.log('[LOG] Finished updating availability');
          EOF

      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git add .

          git status 
          
          git commit -m 'Reset monthly availability' || echo 'No changes to commit!'

      - name: Push changes
        run: |
          git push
